Repository tensorflow/tfjs-core, pull requests merged in 2018-12, with the labels that each got.

#1418 Implement packed depthwiseConv.
  src/environment.ts
  src/environment_util.ts
  src/kernels/backend_webgl.ts
  src/kernels/webgl/conv_packed_gpu_depthwise.ts
  src/kernels/webgl/tex_util.ts
  src/ops/conv2d_depthwise_test.ts
Labels: perf

#1439 fixed scatter nd error
  src/ops/scatter_nd_test.ts
  src/ops/scatter_nd_util.ts
Labels: bug

#1445 Rewrite prelu as binary op for performance.
  src/kernels/backend.ts
  src/kernels/backend_cpu.ts
  src/kernels/backend_webgl.ts
  src/kernels/webgl/binaryop_gpu.ts
  src/ops/relu_ops.ts
Labels: perf

#1434 Simplify logic for allocating array for packed textures.
  src/kernels/backend_webgl.ts
  src/kernels/webgl/gpgpu_util.ts
  src/kernels/webgl/shader_compiler.ts
  src/kernels/webgl/tex_util.ts
  src/kernels/webgl/webgl_util.ts
  src/ops/batchnorm_test.ts
  src/ops/conv2d_test.ts
Labels: cleanup

#1447 Fix invalid isPacked state when texture is released.
  src/kernels/backend_webgl.ts
  src/kernels/backend_webgl_test.ts
Labels: BUG

#1457 Simplify broadcasting logic in compiler
  src/kernels/webgl/batchnorm_gpu.ts
  src/kernels/webgl/batchnorm_packed_gpu.ts
  src/kernels/webgl/binaryop_complex_gpu.ts
  src/kernels/webgl/binaryop_gpu.ts
  src/kernels/webgl/gpgpu_math.ts
  src/kernels/webgl/reshape_packed_test.ts
  src/kernels/webgl/shader_compiler.ts
  src/ops/arithmetic_test.ts
  src/ops/broadcast_util.ts
  src/ops/broadcast_util_test.ts
Labels: INTERNAL

#1453 Switch the paging flag to be a single environment flag representing megabytes before paging.
  integration_tests/benchmarks/benchmark.html
  src/environment.ts
  src/environment_test.ts
  src/environment_util.ts
  src/kernels/backend_webgl.ts
Labels: PERF

#1423 Add packed arithmetic binary operation kernel. (#951)
  src/environment.ts
  src/environment_util.ts
  src/kernels/backend_webgl.ts
  src/kernels/webgl/binaryop_gpu.ts
  src/kernels/webgl/binaryop_packed_gpu.ts
  src/kernels/webgl/shader_compiler.ts
  src/ops/arithmetic_packed_test.ts
  src/ops/matmul_test.ts
Labels: PERF

#1466 In DEBUG mode check downloads for Infinity and check uploads for NaN / Infinity / underflow / overflow
  src/debug_mode_test.ts
  src/kernels/backend_webgl.ts
  src/kernels/webgl/webgl_util.ts
  src/ops/tensor_ops.ts
  src/profiler.ts
  src/util.ts
  src/util_test.ts
Labels: DEV, FEATURE
