Repository tensorflow/tfjs-core, pull requests merged in 2019-08, with the labels that each got.

#1869 Update tfjs-core to 1.2.7.
  package.json
  src/version.ts
Labels: INTERNAL

#1867 Fuse prelu activation.
  src/backends/backend.ts
  src/backends/cpu/backend_cpu.ts
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/conv_gpu.ts
  src/backends/webgl/mulmat_packed_gpu.ts
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
  src/ops/fused_util.ts
Labels: FEATURE, PERF

#1256 add tf.diag
  src/backends/backend.ts
  src/backends/cpu/backend_cpu.ts
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/diag_gpu.ts
  src/ops/diag.ts
  src/ops/diag_test.ts
  src/ops/ops.ts
  src/tests.ts
Labels: cla: yes

#1365 Add support for generating pseudorandom numbers drawn from a gamma distribution
  src/ops/array_ops.ts
  src/ops/array_ops_test.ts
  src/ops/rand.ts
  src/ops/rand_test.ts
Labels: cla: yes

#1871 Fix unit test to not use tf.tidy in boolean mask test.
  src/ops/boolean_mask.ts
  src/ops/boolean_mask_test.ts
Labels: cla: yes

#1791 Add NCHW dataFormat support for conv2d
  src/backends/cpu/backend_cpu.ts
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/conv_backprop_gpu.ts
  src/backends/webgl/conv_gpu.ts
  src/backends/webgl/im2col_packed_gpu.ts
  src/ops/conv.ts
  src/ops/conv2d_test.ts
  src/ops/conv_util.ts
  src/ops/conv_util_test.ts
Labels: cla: yes

#1872 Reduce the size of the gramSchmidt-non-tiny test
  src/backends/webgl/webgl_ops_test.ts
Labels: cla: yes

#1870 Add react native unit tests to ci
  cloudbuild.yml
  tfjs-react-native/karma.conf.js
  tfjs-react-native/package.json
  tfjs-react-native/scripts/test-ci.sh
  tfjs-react-native/yarn.lock
Labels: cla: yes

#1778 Add avgPool3d & maxPool3d
  src/backends/backend.ts
  src/backends/cpu/backend_cpu.ts
  src/backends/webgl/avg_pool_backprop_gpu.ts
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/max_pool_backprop_gpu.ts
  src/backends/webgl/pool_gpu.ts
  src/ops/conv_util.ts
  src/ops/conv_util_test.ts
  src/ops/pool.ts
  src/ops/pool_test.ts
Labels: cla: yes

#1873 Cleanup intopk to remove it as a kernel.
  src/backends/backend.ts
  src/backends/cpu/backend_cpu.ts
  src/backends/inTopK_impl.ts
  src/backends/webgl/backend_webgl.ts
  src/ops/in_top_k.ts
  src/ops/in_top_k_test.ts
  src/ops/ops.ts
  src/tests.ts
Labels: cla: yes

#1473 Fixed division by zero in QR decomposition. Issue #1058
  src/io/passthrough_test.ts
  src/jasmine_util.ts
  src/ops/concat_test.ts
  src/ops/linalg_ops.ts
  src/ops/linalg_ops_test.ts
Labels: cla: yes

#1782 Add non-default noiseShape support to dropout op
  src/ops/dropout.ts
  src/ops/dropout_test.ts
  src/ops/dropout_util.ts
  src/ops/dropout_util_test.ts
  src/tests.ts
Labels: cla: yes

#1629 ADD: conv3dtranspose
  .vscode/settings.json
  src/ops/conv.ts
  src/ops/conv3d_transpose_test.ts
  src/tests.ts
Labels: cla: yes

#1877 Wait for yarn in webgpu / react native CI cloudbuild.yml.
  cloudbuild.yml
Labels: cla: yes

#1875 Add memory info to benchmarks page.
  benchmarks/index.html
Labels: cla: yes

#1746 Add stft op
  src/ops/signal_ops.ts
  src/ops/signal_ops_test.ts
Labels: cla: yes

#1878 Add information about the monorepo to README and the pull request template.
  README.md
  pull_request_template.md
Labels: cla: yes
