Repository tensorflow/tfjs-core, pull requests merged in 2019-07, with the labels that each got.

#1828 In WebGL render image to canvas as part of fromPixels to match CPU.
  src/backends/webgl/backend_webgl.ts
  src/ops/array_ops_test.ts
Labels: BUG

#1822 [webgpu] Add buffer manager for buffer reuse.
  tfjs-webgpu/src/backend_webgpu.ts
  tfjs-webgpu/src/backend_webgpu_test.ts
  tfjs-webgpu/src/buffer_manager.ts
Labels: FEATURE

#1835 [webgpu] Update docs - custom Chromium build no longer needed.
  tfjs-webgpu/README.md
Labels: DOC

#1842 Update tfjs-core to 1.2.3.
  package.json
  src/version.ts
Labels: INTERNAL

#1845 Change matMul expression to fix Windows inconsistency.
  src/backends/webgl/mulmat_packed_gpu.ts
Labels: BUG

#1848 Undo change where we add an arraybuffer response type to the request.
  src/io/weights_loader.ts
  src/io/weights_loader_test.ts
Labels: BUG

#1850 Manually unroll loop to fix D3D compilation errors.
  src/backends/webgl/im2col_packed_gpu.ts
Labels: BUG

#1851 [webgpu] Update types.
  tfjs-webgpu/package.json
  tfjs-webgpu/src/backend_webgpu.ts
  tfjs-webgpu/src/kernels/webgpu_program.ts
  tfjs-webgpu/yarn.lock
Labels: FEATURE

#1853 Update tfjs-core to 1.2.5.
  package.json
  src/version.ts
Labels: INTERNAL

#1858 Use idiv in flat indexing.
  src/backends/webgl/encode_matrix_gpu.ts
  src/backends/webgl/encode_matrix_packed_gpu.ts
Labels: BUG

#1861 Fix serialized classNames for Optimizers
  src/optimizers/adadelta_optimizer.ts
  src/optimizers/momentum_optimizer.ts
  src/optimizers/rmsprop_optimizer.ts
  src/optimizers/sgd_optimizer.ts
Labels: BUG, INTERNAL

#1859 Fuse conv2d with bias and activation.
  src/backends/backend.ts
  src/backends/cpu/backend_cpu.ts
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/conv_gpu.ts
  src/ops/conv.ts
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
Labels: FEATURE, PERF
