Repository tensorflow/tfjs-core, pull requests merged in 2019-03, with the labels that each got.

#1598 For matMul gradient broadcasting logic must account for temporary reshaping of inputs.
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
Labels: BUG

#1599 Add error messaging when the model.json parsing fails.
  src/io/browser_http.ts
  src/io/browser_http_test.ts
  src/io/weights_loader.ts
Labels: UX

#1605 Use unpacked div always while we figure out why packed div produces NaNs.
  src/kernels/backend_webgl.ts
Labels: BUG

#1610 If matMul is going to be unpacked, then don't try to avoid expensive reshape in pointwise conv.
  src/kernels/backend_webgl.ts
  src/ops/conv2d_test.ts
Labels: BUG

#1618 Call rollup instead of yarn rollup as part of publish-local script.
  package.json
Labels: DEV

#1602 Remove command to log benchmarks since it's happening in union now.
  .travis.yml
  benchmarks/index.html
  integration_tests/benchmarks/README.md
  integration_tests/benchmarks/batchnormalization3d_benchmark.ts
  integration_tests/benchmarks/benchmark_test.ts
  integration_tests/benchmarks/benchmark_travis.sh
  integration_tests/benchmarks/conv_benchmarks.ts
  integration_tests/benchmarks/firebase.ts
  integration_tests/benchmarks/firebase_types.ts
  integration_tests/benchmarks/karma.conf.js
  integration_tests/benchmarks/matmul_benchmarks.ts
  integration_tests/benchmarks/mobilenet_benchmarks.ts
  integration_tests/benchmarks/package.json
  integration_tests/benchmarks/pool_benchmarks.ts
  integration_tests/benchmarks/reduction_ops_benchmark.ts
  integration_tests/benchmarks/test_util.ts
  integration_tests/benchmarks/tsconfig.json
  integration_tests/benchmarks/types.ts
  integration_tests/benchmarks/ui/benchmark_run_groups.ts
  integration_tests/benchmarks/ui/benchmarks.ts
  integration_tests/benchmarks/ui/chartjs.d.ts
  integration_tests/benchmarks/ui/demo-header.html
  integration_tests/benchmarks/ui/index.html
  integration_tests/benchmarks/ui/math-benchmark.html
  integration_tests/benchmarks/ui/package.json
  integration_tests/benchmarks/ui/polymer-spec.ts
  integration_tests/benchmarks/ui/tsconfig.json
  integration_tests/benchmarks/unary_ops_benchmark.ts
  integration_tests/benchmarks/util.ts
  integration_tests/benchmarks/yarn.lock
Labels: INTERNAL

#1604 Improve disposal of tensors during training
  karma.conf.js
  src/engine.ts
  src/engine_test.ts
  src/globals.ts
  src/gradients.ts
  src/index.ts
  src/kernels/webgl/webgl_custom_op_test.ts
  src/ops/arithmetic_test.ts
  src/ops/array_ops_test.ts
  src/ops/batchnorm.ts
  src/ops/batchnorm_test.ts
  src/ops/binary_ops.ts
  src/ops/binary_ops_test.ts
  src/ops/compare_ops_test.ts
  src/ops/concat_test.ts
  src/ops/conv.ts
  src/ops/conv1d_test.ts
  src/ops/conv2d_depthwise_test.ts
  src/ops/conv2d_test.ts
  src/ops/conv2d_transpose_test.ts
  src/ops/conv3d_test.ts
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
  src/ops/image_ops.ts
  src/ops/logical_ops.ts
  src/ops/logical_ops_test.ts
  src/ops/loss_ops.ts
  src/ops/lrn.ts
  src/ops/lrn_test.ts
  src/ops/matmul.ts
  src/ops/matmul_test.ts
  src/ops/pad_test.ts
  src/ops/pool.ts
  src/ops/pool_test.ts
  src/ops/reduction_ops.ts
  src/ops/reduction_ops_test.ts
  src/ops/relu_ops.ts
  src/ops/resize_bilinear_test.ts
  src/ops/resize_nearest_neighbor_test.ts
  src/ops/reverse_test.ts
  src/ops/segment_ops.ts
  src/ops/segment_ops_test.ts
  src/ops/slice_test.ts
  src/ops/softmax.ts
  src/ops/softmax_test.ts
  src/ops/transpose_test.ts
  src/ops/unary_ops.ts
  src/ops/unary_ops_test.ts
  src/tape.ts
  src/tape_test.ts
  src/tensor_types.ts
  src/tensor_util_env.ts
Labels: BUG

#1640 Modify im2col to use packed texture inputs.
  src/kernels/backend_webgl.ts
  src/kernels/webgl/im2col_packed_gpu.ts
Labels: PERF
