Repository tensorflow/tfjs-core, pull requests merged in 2019-06, with the labels that each got.

#1777 Generalize fromPixels for all tensor creation.
  benchmarks/index.html
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/encode_matrix_gpu.ts
  src/backends/webgl/encode_matrix_packed_gpu.ts
  src/backends/webgl/from_pixels_packed_gpu.ts
  src/backends/webgl/gpgpu_context.ts
  src/backends/webgl/gpgpu_context_test.ts
  src/backends/webgl/gpgpu_util.ts
  src/backends/webgl/reshape_packed_gpu.ts
  src/backends/webgl/shader_compiler_util.ts
  src/backends/webgl/tex_util.ts
  src/backends/webgl/tex_util_test.ts
  src/backends/webgl/texture_manager.ts
Labels: FEATURE, PERF

#1783 Hit TFHub in benchmarks.
  benchmarks/index.html
Labels: DEV

#1786 When disposing variable set internal isDisposed flag.
  src/tensor.ts
Labels: BUG

#1784 Update tfjs-core to 1.2.1.
  package.json
  src/version.ts
Labels: INTERNAL

#1793 Use texel dtype appropriate for ArrayBufferView dtype when uploading dense matrix to texture.
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/encode_matrix_gpu.ts
  src/backends/webgl/encode_matrix_packed_gpu.ts
  src/backends/webgl/gpgpu_util.ts
Labels: PERF

#1796 Disable packed depthwiseConv.
  src/backends/webgl/flags_webgl.ts
  src/backends/webgl/flags_webgl_test.ts
Labels: PERF

#1800 Use ints instead of floats for getting flat index.
  src/backends/webgl/backend_webgl_test.ts
  src/backends/webgl/shader_compiler.ts
  src/backends/webgl/shader_compiler_util.ts
Labels: BUG

#1798 Decode textures on the GPU.
  src/backends/webgl/backend_webgl.ts
  src/backends/webgl/decode_matrix_gpu.ts
  src/backends/webgl/decode_matrix_packed_gpu.ts
  src/backends/webgl/gpgpu_context.ts
  src/backends/webgl/gpgpu_context_test.ts
  src/backends/webgl/gpgpu_math.ts
  src/backends/webgl/gpgpu_util.ts
  src/backends/webgl/gpgpu_util_test.ts
  src/backends/webgl/pack_gpu.ts
  src/backends/webgl/tex_util.ts
  src/backends/webgl/tex_util_test.ts
  src/backends/webgl/webgl_util.ts
Labels: PERF

#1813 [webgpu] Enable delayed execution mode.
  tfjs-webgpu/src/backend_webgpu.ts
  tfjs-webgpu/src/matmul_test.ts
Labels: FEATURE, PERF

#1806 Update tfjs-core to 1.2.2.
  package.json
  src/version.ts
Labels: INTERNAL

#1815 [webgpu] Count byte usage.
  src/backends/backend_util.ts
  tfjs-webgpu/src/backend_webgpu.ts
  tfjs-webgpu/src/backend_webgpu_test.ts
  tfjs-webgpu/src/setup_test.ts
Labels: FEATURE
