Repository tensorflow/tfjs-core, pull requests merged in 2019-01, with the labels that each got.

#1482 Remove pull request template.
  PULL_REQUEST_TEMPLATE.md
Labels: INTERNAL

#1489 Enable true squarification when logical dimensions exceed texture size limits.
  src/kernels/backend_webgl.ts
  src/kernels/webgl/gpgpu_util.ts
  src/kernels/webgl/shader_compiler.ts
  src/kernels/webgl/webgl_util_test.ts
  src/ops/batchnorm_test.ts
  src/ops/binary_ops_test.ts
  src/ops/matmul_test.ts
  src/ops/unary_ops_test.ts
  src/util.ts
  src/util_test.ts
Labels: BUG

#1438 Support high rank indices for gather op
  src/ops/array_ops_test.ts
  src/ops/segment_ops.ts
  src/ops/segment_util.ts
  src/tensor.ts
Labels: BUG, FEATURE

#1475 Fuse matMul with activation and bias for performance.
  src/kernels/backend.ts
  src/kernels/backend_cpu.ts
  src/kernels/backend_webgl.ts
  src/kernels/webgl/mulmat_gpu.ts
  src/kernels/webgl/mulmat_packed_gpu.ts
  src/kernels/webgl/unaryop_gpu.ts
  src/kernels/webgl/unaryop_packed_gpu.ts
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
  src/ops/fused_util.ts
  src/ops/ops.ts
Labels: FEATURE, PERF

#1499 Enable packed depthwiseConv for arbitrary dilation / padding.
  src/kernels/backend_webgl.ts
  src/kernels/webgl/conv_packed_gpu_depthwise.ts
  src/ops/conv2d_depthwise_test.ts
Labels: PERF

#1498 Packed pad operation.
  src/environment.ts
  src/environment_util.ts
  src/kernels/backend_webgl.ts
  src/kernels/webgl/pad_packed_gpu.ts
  src/kernels/webgl/shader_compiler.ts
Labels: PERF

#1505 Pack unary ops.
  src/kernels/backend_webgl.ts
  src/kernels/webgl/shader_compiler.ts
  src/kernels/webgl/unaryop_packed_gpu.ts
Labels: PERF

#1506 Wrap cropAndResize with an `op` decorator
  src/engine.ts
  src/ops/image_ops.ts
Labels: BUG

#1502 Add partial support for broadcasting of bias in fusedMatMul.
  src/kernels/backend.ts
  src/kernels/backend_cpu.ts
  src/kernels/backend_webgl.ts
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
  src/ops/fused_util.ts
Labels: PERF

#1509 Support packed broadcasting.
  src/kernels/backend_webgl.ts
  src/kernels/webgl/binaryop_packed_gpu.ts
  src/kernels/webgl/shader_compiler.ts
  src/ops/fused_ops.ts
  src/ops/fused_test.ts
Labels: PERF

#1511 Add test for batchnorm with broadcasted inputs.
  src/ops/batchnorm_test.ts
Labels: INTERNAL

#1513 Replace vectorized packed div with channel-wise implementation to fix layers tests.
  src/kernels/webgl/binaryop_packed_gpu.ts
Labels: BUG

#1518 Add test that catches packed division failure on linux.
  src/kernels/webgl/binaryop_gpu.ts
  src/kernels/webgl/binaryop_packed_gpu.ts
  src/ops/binary_ops_test.ts
Labels: INTERNAL

#1519 Make WEBGL_PACK default to true.
  scripts/test-travis.sh
  src/engine.ts
  src/environment.ts
  src/jasmine_util.ts
  src/kernels/backend.ts
  src/kernels/backend_webgl.ts
  src/tensor.ts
Labels: PERF
